import type { NextPage } from "next";
import Head from "next/head";

type Props = {
  result: {
    name: string;
    road: string;
    building_number: string;
  };
};

const Home: NextPage<Props> = ({ result }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

export default Home;
